//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.14 at 11:37:50 PM CEST 
//


package factory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="empleats">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="empleat">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cognom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="anys_treball" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="sou" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="clients">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="client">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nif" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cognom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cataleg">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="producte">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="preu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="factures">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="factura">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="client_nif" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="id_producte" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="preu_unitat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="preu_total" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="iva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "empleats",
    "clients",
    "cataleg",
    "factures"
})
@XmlRootElement(name = "empresa")
public class Empresa {

    @XmlElement(required = true)
    protected Empresa.Empleats empleats;
    @XmlElement(required = true)
    protected Empresa.Clients clients;
    @XmlElement(required = true)
    protected Empresa.Cataleg cataleg;
    @XmlElement(required = true)
    protected Empresa.Factures factures;

    /**
     * Gets the value of the empleats property.
     * 
     * @return
     *     possible object is
     *     {@link Empresa.Empleats }
     *     
     */
    public Empresa.Empleats getEmpleats() {
        return empleats;
    }

    /**
     * Sets the value of the empleats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empresa.Empleats }
     *     
     */
    public void setEmpleats(Empresa.Empleats value) {
        this.empleats = value;
    }

    /**
     * Gets the value of the clients property.
     * 
     * @return
     *     possible object is
     *     {@link Empresa.Clients }
     *     
     */
    public Empresa.Clients getClients() {
        return clients;
    }

    /**
     * Sets the value of the clients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empresa.Clients }
     *     
     */
    public void setClients(Empresa.Clients value) {
        this.clients = value;
    }

    /**
     * Gets the value of the cataleg property.
     * 
     * @return
     *     possible object is
     *     {@link Empresa.Cataleg }
     *     
     */
    public Empresa.Cataleg getCataleg() {
        return cataleg;
    }

    /**
     * Sets the value of the cataleg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empresa.Cataleg }
     *     
     */
    public void setCataleg(Empresa.Cataleg value) {
        this.cataleg = value;
    }

    /**
     * Gets the value of the factures property.
     * 
     * @return
     *     possible object is
     *     {@link Empresa.Factures }
     *     
     */
    public Empresa.Factures getFactures() {
        return factures;
    }

    /**
     * Sets the value of the factures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empresa.Factures }
     *     
     */
    public void setFactures(Empresa.Factures value) {
        this.factures = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="producte">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="preu" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "producte"
    })
    public static class Cataleg {

        @XmlElement(required = true)
        protected Empresa.Cataleg.Producte producte;

        /**
         * Gets the value of the producte property.
         * 
         * @return
         *     possible object is
         *     {@link Empresa.Cataleg.Producte }
         *     
         */
        public Empresa.Cataleg.Producte getProducte() {
            return producte;
        }

        /**
         * Sets the value of the producte property.
         * 
         * @param value
         *     allowed object is
         *     {@link Empresa.Cataleg.Producte }
         *     
         */
        public void setProducte(Empresa.Cataleg.Producte value) {
            this.producte = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="preu" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "nom",
            "preu",
            "stock"
        })
        public static class Producte {

            @XmlElement(required = true)
            protected String id;
            @XmlElement(required = true)
            protected String nom;
            @XmlElement(required = true)
            protected String preu;
            @XmlElement(required = true)
            protected String stock;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the nom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNom() {
                return nom;
            }

            /**
             * Sets the value of the nom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNom(String value) {
                this.nom = value;
            }

            /**
             * Gets the value of the preu property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPreu() {
                return preu;
            }

            /**
             * Sets the value of the preu property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPreu(String value) {
                this.preu = value;
            }

            /**
             * Gets the value of the stock property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStock() {
                return stock;
            }

            /**
             * Sets the value of the stock property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStock(String value) {
                this.stock = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="client">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nif" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cognom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "client"
    })
    public static class Clients {

        @XmlElement(required = true)
        protected Empresa.Clients.Client client;

        /**
         * Gets the value of the client property.
         * 
         * @return
         *     possible object is
         *     {@link Empresa.Clients.Client }
         *     
         */
        public Empresa.Clients.Client getClient() {
            return client;
        }

        /**
         * Sets the value of the client property.
         * 
         * @param value
         *     allowed object is
         *     {@link Empresa.Clients.Client }
         *     
         */
        public void setClient(Empresa.Clients.Client value) {
            this.client = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nif" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cognom" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nif",
            "nom",
            "cognom"
        })
        public static class Client {

            @XmlElement(required = true)
            protected String nif;
            @XmlElement(required = true)
            protected String nom;
            @XmlElement(required = true)
            protected String cognom;

            /**
             * Gets the value of the nif property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNif() {
                return nif;
            }

            /**
             * Sets the value of the nif property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNif(String value) {
                this.nif = value;
            }

            /**
             * Gets the value of the nom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNom() {
                return nom;
            }

            /**
             * Sets the value of the nom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNom(String value) {
                this.nom = value;
            }

            /**
             * Gets the value of the cognom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCognom() {
                return cognom;
            }

            /**
             * Sets the value of the cognom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCognom(String value) {
                this.cognom = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="empleat">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cognom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="anys_treball" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="sou" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "empleat"
    })
    public static class Empleats {

        @XmlElement(required = true)
        protected Empresa.Empleats.Empleat empleat;

        /**
         * Gets the value of the empleat property.
         * 
         * @return
         *     possible object is
         *     {@link Empresa.Empleats.Empleat }
         *     
         */
        public Empresa.Empleats.Empleat getEmpleat() {
            return empleat;
        }

        /**
         * Sets the value of the empleat property.
         * 
         * @param value
         *     allowed object is
         *     {@link Empresa.Empleats.Empleat }
         *     
         */
        public void setEmpleat(Empresa.Empleats.Empleat value) {
            this.empleat = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cognom" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="anys_treball" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="sou" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "nom",
            "cognom",
            "anysTreball",
            "sou"
        })
        public static class Empleat {

            @XmlElement(required = true)
            protected String id;
            @XmlElement(required = true)
            protected String nom;
            @XmlElement(required = true)
            protected String cognom;
            @XmlElement(name = "anys_treball", required = true)
            protected String anysTreball;
            @XmlElement(required = true)
            protected String sou;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the nom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNom() {
                return nom;
            }

            /**
             * Sets the value of the nom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNom(String value) {
                this.nom = value;
            }

            /**
             * Gets the value of the cognom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCognom() {
                return cognom;
            }

            /**
             * Sets the value of the cognom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCognom(String value) {
                this.cognom = value;
            }

            /**
             * Gets the value of the anysTreball property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAnysTreball() {
                return anysTreball;
            }

            /**
             * Sets the value of the anysTreball property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAnysTreball(String value) {
                this.anysTreball = value;
            }

            /**
             * Gets the value of the sou property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSou() {
                return sou;
            }

            /**
             * Sets the value of the sou property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSou(String value) {
                this.sou = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="factura">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="client_nif" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="id_producte" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="preu_unitat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="preu_total" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="iva" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "factura"
    })
    public static class Factures {

        @XmlElement(required = true)
        protected Empresa.Factures.Factura factura;

        /**
         * Gets the value of the factura property.
         * 
         * @return
         *     possible object is
         *     {@link Empresa.Factures.Factura }
         *     
         */
        public Empresa.Factures.Factura getFactura() {
            return factura;
        }

        /**
         * Sets the value of the factura property.
         * 
         * @param value
         *     allowed object is
         *     {@link Empresa.Factures.Factura }
         *     
         */
        public void setFactura(Empresa.Factures.Factura value) {
            this.factura = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="client_nif" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="id_producte" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="preu_unitat" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="preu_total" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="iva" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clientNif",
            "idProducte",
            "preuUnitat",
            "preuTotal",
            "iva"
        })
        public static class Factura {

            @XmlElement(name = "client_nif", required = true)
            protected String clientNif;
            @XmlElement(name = "id_producte", required = true)
            protected String idProducte;
            @XmlElement(name = "preu_unitat", required = true)
            protected String preuUnitat;
            @XmlElement(name = "preu_total", required = true)
            protected String preuTotal;
            @XmlElement(required = true)
            protected String iva;

            /**
             * Gets the value of the clientNif property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClientNif() {
                return clientNif;
            }

            /**
             * Sets the value of the clientNif property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClientNif(String value) {
                this.clientNif = value;
            }

            /**
             * Gets the value of the idProducte property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdProducte() {
                return idProducte;
            }

            /**
             * Sets the value of the idProducte property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdProducte(String value) {
                this.idProducte = value;
            }

            /**
             * Gets the value of the preuUnitat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPreuUnitat() {
                return preuUnitat;
            }

            /**
             * Sets the value of the preuUnitat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPreuUnitat(String value) {
                this.preuUnitat = value;
            }

            /**
             * Gets the value of the preuTotal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPreuTotal() {
                return preuTotal;
            }

            /**
             * Sets the value of the preuTotal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPreuTotal(String value) {
                this.preuTotal = value;
            }

            /**
             * Gets the value of the iva property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIva() {
                return iva;
            }

            /**
             * Sets the value of the iva property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIva(String value) {
                this.iva = value;
            }

        }

    }

}
