//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.14 at 11:37:50 PM CEST 
//


package factory;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the factory package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: factory
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Empresa }
     * 
     */
    public Empresa createEmpresa() {
        return new Empresa();
    }

    /**
     * Create an instance of {@link Empresa.Factures }
     * 
     */
    public Empresa.Factures createEmpresaFactures() {
        return new Empresa.Factures();
    }

    /**
     * Create an instance of {@link Empresa.Cataleg }
     * 
     */
    public Empresa.Cataleg createEmpresaCataleg() {
        return new Empresa.Cataleg();
    }

    /**
     * Create an instance of {@link Empresa.Clients }
     * 
     */
    public Empresa.Clients createEmpresaClients() {
        return new Empresa.Clients();
    }

    /**
     * Create an instance of {@link Empresa.Empleats }
     * 
     */
    public Empresa.Empleats createEmpresaEmpleats() {
        return new Empresa.Empleats();
    }

    /**
     * Create an instance of {@link Empresa.Factures.Factura }
     * 
     */
    public Empresa.Factures.Factura createEmpresaFacturesFactura() {
        return new Empresa.Factures.Factura();
    }

    /**
     * Create an instance of {@link Empresa.Cataleg.Producte }
     * 
     */
    public Empresa.Cataleg.Producte createEmpresaCatalegProducte() {
        return new Empresa.Cataleg.Producte();
    }

    /**
     * Create an instance of {@link Empresa.Clients.Client }
     * 
     */
    public Empresa.Clients.Client createEmpresaClientsClient() {
        return new Empresa.Clients.Client();
    }

    /**
     * Create an instance of {@link Empresa.Empleats.Empleat }
     * 
     */
    public Empresa.Empleats.Empleat createEmpresaEmpleatsEmpleat() {
        return new Empresa.Empleats.Empleat();
    }

}
